//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistemas_de_Prestamos.conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fondo
    {
        public int FondoID { get; set; }
        public decimal MontoDisponible { get; set; }
    }
}
