//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistemas_de_Prestamos.conexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaPrestamosEntities1 : DbContext
    {
        public SistemaPrestamosEntities1()
            : base("name=SistemaPrestamosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Fondo> Fondo { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
    }
}
