//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistemas_de_Prestamos.conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagoID { get; set; }
        public int PrestamoID { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public decimal MontoPagado { get; set; }
        public Nullable<bool> Mora { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
